namespace :db do
  desc "Fill database with the data from the site of febradan"
  #  +   "http://www.febraban.org.br/arquivo/bancos/sitebancos2-0.asp"
  task banks: :environment do
    Bank.create!(number:"104", name: "Caixa Econômica Federal")
    Bank.create!(number:"107", name: "Banco BBM S.A.")
    Bank.create!(number:"119", name: "Banco Western Union do Brasil S.A.")
    Bank.create!(number:"125", name: "Brasil Plural S.A. - Banco Múltiplo")
    Bank.create!(number:"184", name: "Banco Itaú BBA S.A.")
    Bank.create!(number:"204", name: "Banco Bradesco Cartões S.A.")
    Bank.create!(number:"208", name: "Banco BTG Pactual S.A.")
    Bank.create!(number:"214", name: "Banco Dibens S.A.")
    Bank.create!(number:"217", name: "Banco John Deere S.A.")
    Bank.create!(number:"218", name: "Banco Bonsucesso S.A.")
    Bank.create!(number:"222", name: "Banco Credit Agricole Brasil S.A.")
    Bank.create!(number:"224", name: "Banco Fibra S.A.")
    Bank.create!(number:"230", name: "Unicard Banco Múltiplo S.A.")
    Bank.create!(number:"233", name: "Banco Cifra S.A.")
    Bank.create!(number:"237", name: "Banco Bradesco S.A.")
    Bank.create!(number:"246", name: "Banco ABC Brasil S.A.")
    Bank.create!(number:"248", name: "Banco Boavista Interatlântico S.A.")
    Bank.create!(number:"249", name: "Banco Investcred Unibanco S.A.")
    Bank.create!(number:"250", name: "BCV - Banco de Crédito e Varejo S.A.")
    Bank.create!(number:"263", name: "Banco Cacique S.A.")
    Bank.create!(number:"265", name: "Banco Fator S.A.")
    Bank.create!(number:"318", name: "Banco BMG S.A.")
    Bank.create!(number:"320", name: "Banco Industrial e Comercial S.A.")
    Bank.create!(number:"341", name: "Banco Itaú Unibanco S.A.")
    Bank.create!(number:"356", name: "Banco Real S.A.")
    Bank.create!(number:"366", name: "Banco Société Générale Brasil S.A.")
    Bank.create!(number:"370", name: "Banco Mizuho do Brasil S.A.")
    Bank.create!(number:"376", name: "Banco J. P. Morgan S.A.")
    Bank.create!(number:"389", name: "Banco Mercantil do Brasil S.A.")
    Bank.create!(number:"394", name: "Banco Bradesco Financiamentos S.A.")
    Bank.create!(number:"394", name: "Banco Finasa BMC S.A.")
    Bank.create!(number:"399", name: "Banco HSBC Bank Brasil S.A. - Banco Múltiplo")
    Bank.create!(number:"409", name: "Banco UNIBANCO - União de Bancos Brasileiros S.A.")
    Bank.create!(number:"422", name: "Banco Safra S.A.")
    Bank.create!(number:"453", name: "Banco Rural S.A.")
    Bank.create!(number:"456", name: "Banco de Tokyo-Mitsubishi UFJ Brasil S.A.")
    Bank.create!(number:"464", name: "Banco Sumitomo Mitsui Brasileiro S.A.")
    Bank.create!(number:"473", name: "Banco Caixa Geral - Brasil S.A.")
    Bank.create!(number:"477", name: "Banco Citibank S.A.")
    Bank.create!(number:"479", name: "Banco Banco ItaúBank S.A")
    Bank.create!(number:"487", name: "Banco Deutsche Bank S.A. - Banco Alemão")
    Bank.create!(number:"488", name: "Banco JPMorgan Chase Bank")
    Bank.create!(number:"492", name: "Banco ING Bank N.V.")
    Bank.create!(number:"505", name: "Banco Credit Suisse (Brasil) S.A.")
    Bank.create!(number:"600", name: "Banco Luso Brasileiro S.A.")
    Bank.create!(number:"604", name: "Banco Industrial do Brasil S.A.")
    Bank.create!(number:"610", name: "Banco VR S.A.")
    Bank.create!(number:"611", name: "Banco Paulista S.A.")
    Bank.create!(number:"612", name: "Banco Guanabara S.A.")
    Bank.create!(number:"623", name: "Banco Panamericano S.A.")
    Bank.create!(number:"626", name: "Banco Ficsa S.A.")
    Bank.create!(number:"633", name: "Banco Rendimento S.A.")
    Bank.create!(number:"634", name: "Banco Triângulo S.A.")
    Bank.create!(number:"641", name: "Banco Alvorada S.A.")
    Bank.create!(number:"643", name: "Banco Pine S.A.")
    Bank.create!(number:"652", name: "Banco Itaú Unibanco Holding S.A.")
    Bank.create!(number:"653", name: "Banco Indusval S.A.")
    Bank.create!(number:"655", name: "Banco Votorantim S.A.")
    Bank.create!(number:"707", name: "Banco Daycoval S.A.")
    Bank.create!(number:"719", name: "Banco Banif-Banco Internacional do Funchal (Brasil)S.A.")
    Bank.create!(number:"739", name: "Banco BGN S.A.")
    Bank.create!(number:"740", name: "Banco Barclays S.A.")
    Bank.create!(number:"745", name: "Banco Citibank S.A.")
    Bank.create!(number:"747", name: "Banco Rabobank International Brasil S.A.")
    Bank.create!(number:"748", name: "Banco Cooperativo Sicredi S.A.")
    Bank.create!(number:"749", name: "Banco Simples S.A.")
    Bank.create!(number:"751", name: "Banco Scotiabank Brasil S.A. Banco Múltiplo")
    Bank.create!(number:"752", name: "Banco Banco BNP Paribas Brasil S.A.")
    Bank.create!(number:"755", name: "Banco Bank of America Merrill Lynch Banco Múltiplo S.A.")
    Bank.create!(number:"756", name: "Banco Cooperativo do Brasil S.A. - BANCOOB")
    Bank.create!(number:"000", name: "Banco Bankpar S.A.")
    Bank.create!(number:"001", name: "Banco do Brasil S.A.")
    Bank.create!(number:"003", name: "Banco da Amazônia S.A.")
    Bank.create!(number:"004", name: "Banco do Nordeste do Brasil S.A.")
    Bank.create!(number:"012", name: "Banco Standard de Investimentos S.A.")
    Bank.create!(number:"021", name: "Banco BANESTES S.A. Banco do Estado do Espírito Santo")
    Bank.create!(number:"024", name: "Banco de Pernambuco S.A. - BANDEPE")
    Bank.create!(number:"025", name: "Banco Alfa S.A.")
    Bank.create!(number:"029", name: "Banco Banerj S.A.")
    Bank.create!(number:"031", name: "Banco Beg S.A.")
    Bank.create!(number:"033", name: "Banco Santander (Brasil) S.A.")
    Bank.create!(number:"036", name: "Banco Bradesco BBI S.A.")
    Bank.create!(number:"037", name: "Banco do Estado do Pará S.A.")
    Bank.create!(number:"040", name: "Banco Cargill S.A.")
    Bank.create!(number:"041", name: "Banco do Estado do Rio Grande do Sul S.A.")
    Bank.create!(number:"045", name: "Banco Opportunity S.A.")
    Bank.create!(number:"047", name: "Banco do Estado de Sergipe S.A.")
    Bank.create!(number:"062", name: "Banco Hipercard Banco Múltiplo S.A.")
    Bank.create!(number:"063", name: "Banco Banco Ibi S.A. Banco Múltiplo")
    Bank.create!(number:"064", name: "Banco Goldman Sachs do Brasil Banco Múltiplo S.A.")
    Bank.create!(number:"065", name: "Banco Bracce S.A.")
    Bank.create!(number:"069", name: "Banco BPN Brasil Banco Múltiplo S.A.")
    Bank.create!(number:"070", name: "Banco BRB - Banco de Brasília S.A.")
    Bank.create!(number:"072", name: "Banco Rural Mais S.A.")
    Bank.create!(number:"073", name: "Banco BB Banco Popular do Brasil S.A.")
    Bank.create!(number:"074", name: "Banco J. Safra S.A.")
    Bank.create!(number:"075", name: "Banco ABN AMRO S.A.")
    Bank.create!(number:"078", name: "Banco BES Investimento do Brasil S.A.-Banco de Investimento")
    Bank.create!(number:"079", name: "Banco Original do Agronegócio S.A.")
    Bank.create!(number:"095", name: "Banco Confidence de Câmbio S.A.")
    Bank.create!(number:"096", name: "Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A")
    Bank.create!(number:"746", name: "Banco Modal S.A.") 
  end
end

